"""new fields in user model

Revision ID: 330765138600
Revises: 6edc47d071dc
Create Date: 2019-06-11 18:09:52.590547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '330765138600'
down_revision = '6edc47d071dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
